project:
  type: website
  output-dir: docs
  resources: documents

website:
  title: "MPC Information"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true




