---
title: "Welcome to the MPC Information Site"
---

This is where we post selected documents for our students.

## Documents

* Major Programs
  * Mathematics
    * [Mathematics Major Advising Notes](/documents/Math_Fall24.pdf)
    * [College Catalog link](https://catalog.georgetowncollege.edu/mathematics/mathematics-major-mat)
  * Information Technology
    * [Information Technology Advising Notes](/documents/IT_Advising.pdf)
    * [College Catalog link](https://catalog.georgetowncollege.edu/mathematics-physics-and-computer-science/information-technology-major-ift)
  * Web Design
    * [Web Design Advising Notes](/documents/Web_Design_Advising.pdf)
    * [College Catalog link](https://catalog.georgetowncollege.edu/computer-science/web-design-major-wdn)
  
* Minor-only Programs
  * Data Analysis
    * [Data Analysis Notes](/documents/Data_Analysis_Minor_Info.pdf).
    * The above document is discussed in [this AI-generated podcast](https://notebooklm.google.com/notebook/51f3ba39-956d-446c-94fa-a1a2baf997f1/audio).  The two "podcast hosts" combine some genuine insights into the minor along with a lot of hype and at least one outright fib---one host claims to have "heard great things" about one of the courses in the minor---but the podcast is worth checking out in order to compare it critically with the document itself, and to inoculate oneself against a future onslaught of AI-generated marketing.
    * [College Catalog link](https://catalog.georgetowncollege.edu/data-analysis/data-analysis-minor-dta)